# Generated by Django 4.0.4 on 2022-05-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='speciality',
            field=models.CharField(choices=[('mbbs', 'Mbbs'), ('cardiology', 'Cardiology'), ('neurologist', 'Neurologist'), ('surgen', 'Surgen')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
