# Generated by Django 4.0.4 on 2022-05-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='timeslot',
            field=models.IntegerField(choices=[('09:00 am To 10:00 am', '09:00 am To 10:00 am'), ('10:00 am TO 11:00 am', '10:00 am TO 11:00 am'), ('11:00 am To 12:00 am', '11:00 am To 12:00 am'), ('12:00 am To 01:00 pm', '12:00 am To 01:00 pm'), ('02:00 pm To 03:00 pm', '02:00 pm To 03:00 pm'), ('03:00 pm To 04:00 pm', '03:00 pm To 04:00 pm'), ('04:00 pm To 05:00 pm', '04:00 pm To 05:00 pm')]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='weeks',
            field=models.IntegerField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')]),
        ),
    ]
