# Generated by Django 4.0.4 on 2022-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_slot_timeslot_alter_slot_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='timeslot',
            field=models.IntegerField(choices=[('09:00 am To 10:00 am', '09:00 Am To 10:00 Am'), ('10:00 am TO 11:00 am', '10:00 Am TO 11:00 Am'), ('11:00 am To 12:00 am', '11:00 Am To 12:00 Am'), ('12:00 am To 01:00 pm', '12:00 Am To 01:00 Pm'), ('02:00 pm To 03:00 pm', '02:00 Pm To 03:00 Pm'), ('03:00 pm To 04:00 pm', '03:00 Pm To 04:00 Pm'), ('04:00 pm To 05:00 pm', '04:00 Pm To 05:00 Pm')]),
        ),
    ]
